/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/firebase-token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_auth_firebase_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["api_v1_auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["api_v1_auth_me_partial_update"];
        trace?: never;
    };
    "/api/v1/auth/password/change/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_auth_password_change_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["api_v1_auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_companies_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_companies_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{slug}/jobs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_companies_jobs_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_exams_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_exams_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams/{slug}/save/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_exams_save_create"];
        delete: operations["api_v1_exams_save_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams/calendar/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_exams_calendar_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams/cycles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_exams_cycles_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams/cycles/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_exams_cycles_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams/saved/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_exams_saved_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_jobs_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_jobs_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/report/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_jobs_report_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/save/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["api_v1_jobs_save_create"];
        delete: operations["api_v1_jobs_save_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/by-slug/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_jobs_by_slug_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/facets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_jobs_facets_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/saved/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_v1_jobs_saved_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Liveness: the process is up. No dependencies touched. */
        get: operations["healthz_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Readiness: DB responds to SELECT 1 and Redis pings. 503 if either fails. */
        get: operations["readyz_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {unknown} */
        BlankEnum: "";
        /**
         * @description * `central` - Central
         *     * `state` - State
         *     * `banking` - Banking
         *     * `railway` - Railway
         *     * `defence` - Defence
         *     * `testing_agency` - Testing Agency
         * @enum {string}
         */
        BodyTypeEnum: "central" | "state" | "banking" | "railway" | "defence" | "testing_agency";
        CalendarEvent: {
            /** Format: date */
            date: string;
            event_type: string;
            exam_name: string;
            exam_slug: string;
            cycle_label: string;
            stage_name: string | null;
            is_tentative: boolean;
            /** Format: uri */
            official_url: string;
        };
        /**
         * @description * `civil_services` - Civil Services
         *     * `banking` - Banking
         *     * `railway` - Railway
         *     * `ssc` - SSC
         *     * `teaching` - Teaching
         *     * `defence` - Defence
         *     * `engineering` - Engineering
         *     * `medical` - Medical
         *     * `law` - Law
         *     * `state_psc` - State PSC
         *     * `other` - Other
         * @enum {string}
         */
        Category185Enum: "civil_services" | "banking" | "railway" | "ssc" | "teaching" | "defence" | "engineering" | "medical" | "law" | "state_psc" | "other";
        CompanyDetail: {
            name: string;
            slug: string;
            domain: string;
            /** Format: uri */
            logo_url?: string;
            industry?: string;
            hq_location?: string;
            size_bucket?: string;
            readonly open_jobs_count: number;
            description?: string;
            /** Format: uri */
            linkedin_url?: string;
            /** Format: uri */
            career_url?: string;
            is_verified?: boolean;
            /** Format: date-time */
            readonly last_checked_at: string;
        };
        CompanyFacet: {
            slug: string;
            name: string;
            count: number;
        };
        CompanyList: {
            name: string;
            slug: string;
            domain: string;
            /** Format: uri */
            logo_url?: string;
            industry?: string;
            hq_location?: string;
            size_bucket?: string;
            readonly open_jobs_count: number;
        };
        CompanyNested: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            slug: string;
            domain: string;
            /** Format: uri */
            logo_url?: string;
        };
        ConductingBody: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            short_name?: string;
            slug: string;
            body_type: components["schemas"]["BodyTypeEnum"];
            state?: string;
            /** Format: uri */
            website?: string;
            is_active?: boolean;
        };
        /** @description Adds ``role`` + ``email`` claims and tracks login metadata. */
        CustomTokenObtainPairRequest: {
            email: string;
            password: string;
        };
        DepartmentFacet: {
            name: string;
            count: number;
        };
        /**
         * @description * `scrape` - Scrape
         *     * `human` - Human
         *     * `corrigendum` - Corrigendum
         * @enum {string}
         */
        DetectedByEnum: "scrape" | "human" | "corrigendum";
        ExamCycle: {
            /** Format: uuid */
            readonly id: string;
            year: number;
            cycle_label: string;
            status: components["schemas"]["ExamCycleStatusEnum"];
            /** Format: date */
            notification_date?: string | null;
            /** Format: date */
            application_start?: string | null;
            /** Format: date */
            application_end?: string | null;
            /** Format: date */
            fee_last_date?: string | null;
            /** Format: date */
            correction_window_start?: string | null;
            /** Format: date */
            correction_window_end?: string | null;
            /** Format: date */
            result_date?: string | null;
            vacancy_count?: number | null;
            /** Format: uri */
            official_notification_url?: string;
            /** Format: uri */
            notification_pdf_url?: string;
            /** Format: uri */
            source_url?: string;
            extraction_confidence?: number;
            verified_by_human?: boolean;
            is_published?: boolean;
            notes?: string;
            readonly stages: components["schemas"]["ExamStage"][];
            readonly date_changes: components["schemas"]["ExamDateChange"][];
        };
        /**
         * @description * `announced` - Announced
         *     * `notification_out` - Notification Out
         *     * `applications_open` - Applications Open
         *     * `applications_closed` - Applications Closed
         *     * `admit_card_out` - Admit Card Out
         *     * `exam_conducted` - Exam Conducted
         *     * `result_out` - Result Out
         *     * `cancelled` - Cancelled
         *     * `postponed` - Postponed
         * @enum {string}
         */
        ExamCycleStatusEnum: "announced" | "notification_out" | "applications_open" | "applications_closed" | "admit_card_out" | "exam_conducted" | "result_out" | "cancelled" | "postponed";
        ExamDateChange: {
            field_name: string;
            old_value: string;
            new_value: string;
            /** Format: date-time */
            readonly changed_at: string;
            detected_by: components["schemas"]["DetectedByEnum"];
            note?: string;
        };
        ExamDetail: {
            /** Format: uuid */
            readonly id: string;
            slug: string;
            name: string;
            short_name?: string;
            readonly conducting_body: components["schemas"]["ConductingBody"];
            category: components["schemas"]["Category185Enum"];
            level: components["schemas"]["LevelEnum"];
            description?: string;
            /** Format: uri */
            official_url?: string;
            typical_month?: number | null;
            is_active?: boolean;
            readonly cycles: components["schemas"]["ExamCycle"][];
            readonly eligibility: components["schemas"]["ExamEligibility"][];
        };
        ExamEligibility: {
            min_age?: number | null;
            max_age?: number | null;
            /** Format: date */
            age_as_on_date?: string | null;
            age_relaxation?: unknown;
            attempts_general?: number | null;
            attempts_obc?: number | null;
            attempts_sc_st?: number | null;
            attempts_pwbd?: number | null;
            min_qualification?: string;
            allow_final_year_appearing?: boolean;
            nationality_note?: string;
            physical_standards?: unknown;
            verified_by_human?: boolean;
        };
        ExamList: {
            /** Format: uuid */
            readonly id: string;
            slug: string;
            name: string;
            short_name?: string;
            readonly conducting_body: components["schemas"]["ConductingBody"];
            category: components["schemas"]["Category185Enum"];
            level: components["schemas"]["LevelEnum"];
            /** Format: uri */
            official_url?: string;
            typical_month?: number | null;
            is_active?: boolean;
            readonly latest_cycle_status: string | null;
        };
        ExamStage: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            stage_order: number;
            mode: components["schemas"]["ModeEnum"];
            /** Format: date */
            date_start?: string | null;
            /** Format: date */
            date_end?: string | null;
            is_date_tentative?: boolean;
            /** Format: date */
            admit_card_date?: string | null;
            /** Format: date */
            city_intimation_date?: string | null;
            /** Format: date */
            result_date?: string | null;
            duration_minutes?: number | null;
            total_marks?: number | null;
            negative_marking?: string;
            is_qualifying_only?: boolean;
        };
        /**
         * @description * `fresher` - Fresher
         *     * `entry` - Entry
         *     * `mid` - Mid
         *     * `senior` - Senior
         *     * `lead` - Lead
         *     * `unknown` - Unknown
         * @enum {string}
         */
        ExperienceLevelEnum: "fresher" | "entry" | "mid" | "senior" | "lead" | "unknown";
        FacetsResponse: {
            work_mode: components["schemas"]["WorkModeFacet"];
            job_type: components["schemas"]["JobTypeFacet"];
            company: components["schemas"]["CompanyFacet"];
            department: components["schemas"]["DepartmentFacet"];
        };
        FcmToken: {
            fcm_token: string;
        };
        FcmTokenRequest: {
            fcm_token: string;
        };
        JobDetail: {
            /** Format: uuid */
            readonly id: string;
            slug?: string | null;
            title: string;
            readonly company: components["schemas"]["CompanyNested"];
            location_raw?: string;
            work_mode?: components["schemas"]["WorkModeEnum"];
            job_type?: components["schemas"]["JobTypeEnum"];
            department?: string;
            /** Format: date-time */
            posted_at?: string | null;
            /** Format: uri */
            apply_url?: string;
            readonly is_saved: string;
            description?: string;
            readonly description_html_sanitized: string;
            /** Format: uri */
            source_url: string;
            experience_level?: components["schemas"]["ExperienceLevelEnum"];
            extraction_confidence?: number;
            /** Format: date-time */
            readonly scraped_at: string;
            readonly canonical_url: string;
            readonly structured_data: {
                [key: string]: unknown;
            } | null;
        };
        JobList: {
            /** Format: uuid */
            readonly id: string;
            slug?: string | null;
            title: string;
            readonly company: components["schemas"]["CompanyNested"];
            location_raw?: string;
            work_mode?: components["schemas"]["WorkModeEnum"];
            job_type?: components["schemas"]["JobTypeEnum"];
            department?: string;
            /** Format: date-time */
            posted_at?: string | null;
            /** Format: uri */
            apply_url?: string;
            readonly is_saved: string;
        };
        JobReport: {
            /** Format: uuid */
            readonly id: string;
            reason: components["schemas"]["ReasonEnum"];
            detail?: string;
            readonly status: components["schemas"]["JobReportStatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
        };
        JobReportRequest: {
            reason: components["schemas"]["ReasonEnum"];
            detail?: string;
        };
        /**
         * @description * `open` - Open
         *     * `reviewing` - Reviewing
         *     * `resolved` - Resolved
         *     * `rejected` - Rejected
         * @enum {string}
         */
        JobReportStatusEnum: "open" | "reviewing" | "resolved" | "rejected";
        /**
         * @description * `full_time` - Full Time
         *     * `part_time` - Part Time
         *     * `internship` - Internship
         *     * `contract` - Contract
         *     * `temporary` - Temporary
         *     * `freelance` - Freelance
         *     * `unknown` - Unknown
         * @enum {string}
         */
        JobTypeEnum: "full_time" | "part_time" | "internship" | "contract" | "temporary" | "freelance" | "unknown";
        JobTypeFacet: {
            full_time: number;
            part_time: number;
            contract: number;
            internship: number;
            temporary: number;
            freelance: number;
            unknown: number;
        };
        /**
         * @description * `national` - National
         *     * `state` - State
         * @enum {string}
         */
        LevelEnum: "national" | "state";
        /**
         * @description * `online_cbt` - Online CBT
         *     * `offline_omr` - Offline OMR
         *     * `descriptive` - Descriptive
         *     * `interview` - Interview
         *     * `physical` - Physical
         *     * `document` - Document
         * @enum {string}
         */
        ModeEnum: "online_cbt" | "offline_omr" | "descriptive" | "interview" | "physical" | "document";
        PaginatedCompanyListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["CompanyList"][];
        };
        PaginatedExamCycleList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ExamCycle"][];
        };
        PaginatedExamListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ExamList"][];
        };
        PaginatedJobListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["JobList"][];
        };
        PaginatedSavedJobList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["SavedJob"][];
        };
        PasswordChangeRequest: {
            old_password: string;
            new_password: string;
            new_password2: string;
        };
        /**
         * @description * `expired` - Expired
         *     * `broken_link` - Broken Link
         *     * `wrong_details` - Wrong Details
         *     * `duplicate` - Duplicate
         *     * `spam` - Spam
         *     * `other` - Other
         * @enum {string}
         */
        ReasonEnum: "expired" | "broken_link" | "wrong_details" | "duplicate" | "spam" | "other";
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            password2: string;
            full_name?: string;
        };
        /**
         * @description Like the stock refresh serializer but reissues the rotated token through
         *     ``RefreshToken.for_user`` so every rotation-issued refresh gets an
         *     ``OutstandingToken`` row. Stock simplejwt mutates the old token in place and
         *     never records the new jti, which silently breaks "blacklist all outstanding
         *     tokens on password change".
         */
        RotatingRefresh: {
            refresh: string;
            readonly access: string;
        };
        /**
         * @description Like the stock refresh serializer but reissues the rotated token through
         *     ``RefreshToken.for_user`` so every rotation-issued refresh gets an
         *     ``OutstandingToken`` row. Stock simplejwt mutates the old token in place and
         *     never records the new jti, which silently breaks "blacklist all outstanding
         *     tokens on password change".
         */
        RotatingRefreshRequest: {
            refresh: string;
        };
        SaveResponse: {
            detail: string;
        };
        SavedJob: {
            /** Format: uuid */
            readonly id: string;
            readonly job: components["schemas"]["JobList"];
            notes?: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        UserMe: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            full_name?: string;
            phone?: string | null;
            readonly role: string;
            /** Format: date */
            dob?: string | null;
            readonly age: number;
            education?: string;
            category?: components["schemas"]["UserMeCategoryEnum"] | components["schemas"]["BlankEnum"];
            state?: string;
            /** Format: decimal */
            years_of_experience?: string | null;
            /** Format: date-time */
            readonly email_verified_at: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `GEN` - General
         *     * `OBC` - OBC
         *     * `SC` - SC
         *     * `ST` - ST
         *     * `EWS` - EWS
         * @enum {string}
         */
        UserMeCategoryEnum: "GEN" | "OBC" | "SC" | "ST" | "EWS";
        /**
         * @description * `onsite` - Onsite
         *     * `remote` - Remote
         *     * `hybrid` - Hybrid
         *     * `unknown` - Unknown
         * @enum {string}
         */
        WorkModeEnum: "onsite" | "remote" | "hybrid" | "unknown";
        WorkModeFacet: {
            onsite: number;
            remote: number;
            hybrid: number;
            unknown: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_v1_auth_firebase_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FcmTokenRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["FcmTokenRequest"];
                "multipart/form-data": components["schemas"]["FcmTokenRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FcmToken"];
                };
            };
        };
    };
    api_v1_auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomTokenObtainPairRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CustomTokenObtainPairRequest"];
                "multipart/form-data": components["schemas"]["CustomTokenObtainPairRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refresh token blacklisted */
            205: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or expired refresh token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMe"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_auth_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMe"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_auth_password_change_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordChangeRequest"];
                "multipart/form-data": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description Password changed, all tokens blacklisted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RotatingRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RotatingRefreshRequest"];
                "multipart/form-data": components["schemas"]["RotatingRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotatingRefresh"];
                };
            };
        };
    };
    api_v1_auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RegisterRequest"];
                "multipart/form-data": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMe"];
                };
            };
        };
    };
    api_v1_companies_list: {
        parameters: {
            query?: {
                has_open_jobs?: boolean;
                industry?: string;
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description Search */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCompanyListList"];
                };
            };
        };
    };
    api_v1_companies_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDetail"];
                };
            };
        };
    };
    api_v1_companies_jobs_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedJobListList"];
                };
            };
        };
    };
    api_v1_exams_list: {
        parameters: {
            query?: {
                allow_final_year?: boolean;
                applications_open?: boolean;
                body?: string;
                category?: string;
                level?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description Search (trigram) */
                q?: string;
                status?: string;
                upcoming_within_days?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedExamListList"];
                };
            };
        };
    };
    api_v1_exams_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamDetail"];
                };
            };
        };
    };
    api_v1_exams_save_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_exams_save_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_exams_calendar_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarEvent"][];
                };
            };
        };
    };
    api_v1_exams_cycles_list: {
        parameters: {
            query?: {
                exam?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /**
                 * @description * `announced` - Announced
                 *     * `notification_out` - Notification Out
                 *     * `applications_open` - Applications Open
                 *     * `applications_closed` - Applications Closed
                 *     * `admit_card_out` - Admit Card Out
                 *     * `exam_conducted` - Exam Conducted
                 *     * `result_out` - Result Out
                 *     * `cancelled` - Cancelled
                 *     * `postponed` - Postponed
                 */
                status?: "admit_card_out" | "announced" | "applications_closed" | "applications_open" | "cancelled" | "exam_conducted" | "notification_out" | "postponed" | "result_out";
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedExamCycleList"];
                };
            };
        };
    };
    api_v1_exams_cycles_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamCycle"];
                };
            };
        };
    };
    api_v1_exams_saved_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedExamListList"];
                };
            };
        };
    };
    api_v1_jobs_list: {
        parameters: {
            query?: {
                /** @description Company slug */
                company?: string[];
                /** @description icontains */
                department?: string;
                /** @description Boolean */
                has_apply_url?: boolean;
                /** @description Multi-value */
                job_type?: string[];
                /** @description icontains */
                location?: string;
                /** @description posted_at, -posted_at, created_at, -created_at, title */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description ISO date */
                posted_after?: string;
                /** @description Integer */
                posted_within_days?: number;
                /** @description Search */
                q?: string;
                /** @description Multi-value */
                work_mode?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedJobListList"];
                };
            };
        };
    };
    api_v1_jobs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
        };
    };
    api_v1_jobs_report_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobReportRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["JobReportRequest"];
                "multipart/form-data": components["schemas"]["JobReportRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobReport"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_jobs_save_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveResponse"];
                };
            };
        };
    };
    api_v1_jobs_save_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_jobs_by_slug_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
        };
    };
    api_v1_jobs_facets_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacetsResponse"];
                };
            };
        };
    };
    api_v1_jobs_saved_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSavedJobList"];
                };
            };
        };
    };
    healthz_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liveness: process is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readyz_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Readiness: DB + Redis healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
