# Generated by Django 5.2.17 on 2026-08-19 14:56

import uuid

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models

import apps.accounts.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        error_messages={"unique": "A user with that email already exists."},
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid E.164 phone number, e.g. +919876543210.",
                                regex="^\\+[1-9]\\d{1,14}$",
                            )
                        ],
                    ),
                ),
                (
                    "full_name",
                    models.CharField(blank=True, max_length=120, verbose_name="full name"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("user", "User")],
                        db_index=True,
                        default="user",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("education", models.CharField(blank=True, max_length=80)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GEN", "General"),
                            ("OBC", "OBC"),
                            ("SC", "SC"),
                            ("ST", "ST"),
                            ("EWS", "EWS"),
                        ],
                        max_length=8,
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=80)),
                (
                    "years_of_experience",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
                ),
                ("fcm_token", models.CharField(blank=True, max_length=255)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["role"], name="accounts_us_role_1fa9a5_idx"),
                    models.Index(fields=["created_at"], name="accounts_us_created_4734df_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("years_of_experience__isnull", True),
                            ("years_of_experience__gte", 0),
                            _connector="OR",
                        ),
                        name="years_of_experience_non_negative",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"), name="user_email_ci_unique"
                    ),
                ],
            },
            managers=[
                ("objects", apps.accounts.managers.UserManager()),
            ],
        ),
    ]
