# Generated by Django 5.2.17 on 2026-08-19 17:52

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=280, unique=True)),
                ("domain", models.CharField(db_index=True, max_length=255)),
                ("logo_url", models.URLField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("hq_location", models.CharField(blank=True, max_length=255)),
                ("industry", models.CharField(blank=True, max_length=120)),
                ("size_bucket", models.CharField(blank=True, max_length=40)),
                ("linkedin_url", models.URLField(blank=True, max_length=500)),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("main_website", "Main Website"),
                            ("direct_career", "Direct Career"),
                        ],
                        max_length=32,
                    ),
                ),
                ("input_url", models.URLField(max_length=1000)),
                ("career_url", models.URLField(blank=True, db_index=True, max_length=1000)),
                (
                    "career_source_type",
                    models.CharField(
                        choices=[
                            ("own_career_page", "Own Career Page"),
                            ("greenhouse", "Greenhouse"),
                            ("lever", "Lever"),
                            ("ashby", "Ashby"),
                            ("smartrecruiters", "Smartrecruiters"),
                            ("workday", "Workday"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("ats_identifier", models.CharField(blank=True, max_length=255)),
                ("career_url_set_at", models.DateTimeField(blank=True, null=True)),
                (
                    "detection_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("needs_review", "Needs Review"),
                            ("verified", "Verified"),
                            ("not_found", "Not Found"),
                            ("manual", "Manual"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("detection_attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_detection_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("scrape_interval_minutes", models.PositiveIntegerField(default=300)),
                ("next_scrape_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_scraped_at", models.DateTimeField(blank=True, null=True)),
                ("last_successful_scrape_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scrape_health",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("failing", "Failing"),
                            ("paused", "Paused"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("consecutive_failures", models.PositiveSmallIntegerField(default=0)),
                ("total_scrapes", models.PositiveIntegerField(default=0)),
                ("total_failures", models.PositiveIntegerField(default=0)),
                ("last_failure_reason", models.TextField(blank=True)),
                ("last_jobs_seen", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="companies_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "career_url_set_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="career_urls_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companies_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CompanySource",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("url", models.URLField(max_length=1000)),
                ("normalized_url", models.CharField(db_index=True, max_length=1000)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("own_career_page", "Own Career Page"),
                            ("greenhouse", "Greenhouse"),
                            ("lever", "Lever"),
                            ("ashby", "Ashby"),
                            ("smartrecruiters", "Smartrecruiters"),
                            ("workday", "Workday"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=32,
                    ),
                ),
                ("ats_identifier", models.CharField(blank=True, max_length=255)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="companies.company",
                    ),
                ),
                (
                    "set_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectionRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("needs_review", "Needs Review"),
                            ("verified", "Verified"),
                            ("not_found", "Not Found"),
                            ("manual", "Manual"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=32,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("urls_checked", models.PositiveIntegerField(default=0)),
                ("candidates_found", models.PositiveIntegerField(default=0)),
                ("strategies_used", models.JSONField(default=list)),
                ("error_message", models.TextField(blank=True)),
                ("log", models.JSONField(default=list)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_runs",
                        to="companies.company",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CareerCandidateUrl",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("url", models.URLField(max_length=1000)),
                ("normalized_url", models.CharField(db_index=True, max_length=1000)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("robots_txt", "Robots Txt"),
                            ("sitemap", "Sitemap"),
                            ("header_link", "Header Link"),
                            ("footer_link", "Footer Link"),
                            ("common_path", "Common Path"),
                            ("subdomain_guess", "Subdomain Guess"),
                            ("json_ld", "Json Ld"),
                            ("ats_pattern", "Ats Pattern"),
                            ("manual", "Manual"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "guessed_type",
                    models.CharField(
                        choices=[
                            ("own_career_page", "Own Career Page"),
                            ("greenhouse", "Greenhouse"),
                            ("lever", "Lever"),
                            ("ashby", "Ashby"),
                            ("smartrecruiters", "Smartrecruiters"),
                            ("workday", "Workday"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("ats_identifier", models.CharField(blank=True, max_length=255)),
                ("score", models.IntegerField(db_index=True, default=0)),
                ("score_reasons", models.JSONField(default=list)),
                ("page_title", models.CharField(blank=True, max_length=500)),
                ("http_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("sample_job_titles", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("reject_reason", models.CharField(blank=True, max_length=255)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="companies.company",
                    ),
                ),
                (
                    "detection_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidates",
                        to="companies.detectionrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["is_verified", "is_active", "next_scrape_at"], name="idx_company_scheduler"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["detection_status", "-created_at"], name="idx_company_detection_queue"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["scrape_health", "-consecutive_failures"], name="idx_company_health"
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("domain",),
                name="uniq_active_company_domain",
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_deleted", False), models.Q(("career_url", ""), _negated=True)
                ),
                fields=("career_url",),
                name="uniq_active_career_url",
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.CheckConstraint(
                condition=models.Q(("scrape_interval_minutes__gte", 30)),
                name="company_min_scrape_interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_verified", False),
                    models.Q(("career_url", ""), _negated=True),
                    _connector="OR",
                ),
                name="verified_company_requires_career_url",
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.CheckConstraint(
                condition=models.Q(("consecutive_failures__lte", 50)),
                name="company_failure_counter_sane",
            ),
        ),
        migrations.AddConstraint(
            model_name="companysource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("company",),
                name="uniq_current_source_per_company",
            ),
        ),
        migrations.AddConstraint(
            model_name="companysource",
            constraint=models.UniqueConstraint(
                fields=("company", "normalized_url"), name="uniq_company_source_url"
            ),
        ),
        migrations.AddIndex(
            model_name="detectionrun",
            index=models.Index(fields=["company", "-started_at"], name="idx_detection_company"),
        ),
        migrations.AddConstraint(
            model_name="careercandidateurl",
            constraint=models.UniqueConstraint(
                fields=("company", "normalized_url"), name="uniq_candidate_per_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="careercandidateurl",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "approved")),
                fields=("company",),
                name="uniq_approved_candidate_per_company",
            ),
        ),
        migrations.AddConstraint(
            model_name="careercandidateurl",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__gte", 0), ("score__lte", 100)),
                name="candidate_score_range",
            ),
        ),
    ]
