# Generated by Django 5.2.17 on 2026-08-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionrun",
            name="ats_short_circuit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="detectionrun",
            name="checks_used",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="detectionrun",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="detection_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("needs_review", "Needs Review"),
                    ("verified", "Verified"),
                    ("not_found", "Not Found"),
                    ("manual", "Manual"),
                    ("skipped", "Skipped"),
                    ("failed", "Failed"),
                    ("candidates_found", "Candidates Found"),
                    ("no_candidates", "No Candidates"),
                    ("success", "Success"),
                    ("partial", "Partial"),
                ],
                db_index=True,
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="detectionrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("needs_review", "Needs Review"),
                    ("verified", "Verified"),
                    ("not_found", "Not Found"),
                    ("manual", "Manual"),
                    ("skipped", "Skipped"),
                    ("failed", "Failed"),
                    ("candidates_found", "Candidates Found"),
                    ("no_candidates", "No Candidates"),
                    ("success", "Success"),
                    ("partial", "Partial"),
                ],
                db_index=True,
                default="running",
                max_length=32,
            ),
        ),
    ]
