# Generated by Django 5.2.17 on 2026-08-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_detectionrun_ats_short_circuit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="careercandidateurl",
            name="discovered_via",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
