# Generated by Django 5.2.17 on 2026-08-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_careercandidateurl_discovered_via"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="detection_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("needs_review", "Needs Review"),
                    ("verified", "Verified"),
                    ("not_found", "Not Found"),
                    ("manual", "Manual"),
                    ("skipped", "Skipped"),
                    ("failed", "Failed"),
                    ("candidates_found", "Candidates Found"),
                    ("no_candidates", "No Candidates"),
                    ("success", "Success"),
                    ("partial", "Partial"),
                    ("superseded", "Superseded"),
                ],
                db_index=True,
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="detectionrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("needs_review", "Needs Review"),
                    ("verified", "Verified"),
                    ("not_found", "Not Found"),
                    ("manual", "Manual"),
                    ("skipped", "Skipped"),
                    ("failed", "Failed"),
                    ("candidates_found", "Candidates Found"),
                    ("no_candidates", "No Candidates"),
                    ("success", "Success"),
                    ("partial", "Partial"),
                    ("superseded", "Superseded"),
                ],
                db_index=True,
                default="running",
                max_length=32,
            ),
        ),
    ]
