# Generated by Django 5.2.17 on 2026-09-09 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_company_company_name_trgm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="domain",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_deleted", False), models.Q(("ats_identifier", ""), _negated=True)
                ),
                fields=("career_source_type", "ats_identifier"),
                name="uniq_active_ats_identity",
            ),
        ),
    ]
