# Generated by Django 5.2.17 on 2026-09-09 11:24

from django.db import migrations


def backfill_ats_domain(apps, schema_editor):
    Company = apps.get_model("companies", "Company")
    from apps.companies.enums import is_ats_host
    from apps.companies.services import sniff_source_type_from_url

    for company in Company._base_manager.all():
        if company.domain and is_ats_host(company.domain):
            if not company.career_url:
                continue
            source_type, identifier = sniff_source_type_from_url(company.career_url)
            company.domain = None
            company.ats_identifier = identifier
            company.career_source_type = source_type
            company.save(update_fields=["domain", "ats_identifier", "career_source_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_ats_identity_and_domain_nullable"),
    ]

    operations = [
        migrations.RunPython(backfill_ats_domain, migrations.RunPython.noop),
    ]
