# Generated by Django 5.2.17 on 2026-08-19 17:52

import uuid

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("source_job_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("source_url", models.URLField(max_length=1000)),
                ("normalized_source_url", models.CharField(db_index=True, max_length=1000)),
                ("apply_url", models.URLField(blank=True, max_length=1000)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("title", models.CharField(db_index=True, max_length=500)),
                ("title_normalized", models.CharField(db_index=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("description_html", models.TextField(blank=True)),
                ("location_raw", models.CharField(blank=True, max_length=500)),
                ("city", models.CharField(blank=True, db_index=True, max_length=120)),
                ("state", models.CharField(blank=True, max_length=120)),
                ("country", models.CharField(blank=True, max_length=120)),
                (
                    "work_mode",
                    models.CharField(
                        choices=[
                            ("onsite", "Onsite"),
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("internship", "Internship"),
                            ("contract", "Contract"),
                            ("temporary", "Temporary"),
                            ("freelance", "Freelance"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("fresher", "Fresher"),
                            ("entry", "Entry"),
                            ("mid", "Mid"),
                            ("senior", "Senior"),
                            ("lead", "Lead"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "min_experience_years",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
                ),
                (
                    "max_experience_years",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
                ),
                (
                    "salary_min",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "salary_max",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("salary_currency", models.CharField(blank=True, max_length=8)),
                ("salary_period", models.CharField(blank=True, max_length=16)),
                ("department", models.CharField(blank=True, max_length=200)),
                ("skills", models.JSONField(default=list)),
                ("education_required", models.CharField(blank=True, max_length=255)),
                ("posted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("deadline_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("possibly_closed", "Possibly Closed"),
                            ("likely_closed", "Likely Closed"),
                            ("closed", "Closed"),
                            ("draft", "Draft"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("missing_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "first_seen_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("reopened_count", models.PositiveSmallIntegerField(default=0)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("needs_review", models.BooleanField(db_index=True, default=False)),
                ("review_reason", models.CharField(blank=True, max_length=255)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("manually_edited_fields", models.JSONField(default=list)),
                ("is_manual_status", models.BooleanField(default=False)),
                ("extraction_confidence", models.PositiveSmallIntegerField(default=0)),
                ("trust_label", models.CharField(blank=True, max_length=40)),
                ("report_count", models.PositiveIntegerField(default=0)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("save_count", models.PositiveIntegerField(default=0)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="companies.company",
                    ),
                ),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="jobs.job",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_at", "-first_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="JobReport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("expired", "Expired"),
                            ("broken_link", "Broken Link"),
                            ("wrong_info", "Wrong Info"),
                            ("duplicate", "Duplicate"),
                            ("spam", "Spam"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.CharField(blank=True, max_length=500)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="jobs.job",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobStatusEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("missing_count", models.PositiveSmallIntegerField(default=0)),
                ("trigger", models.CharField(max_length=40)),
                ("scrape_run_id", models.UUIDField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_events",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saves",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="job",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="idx_job_search_vector"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["status", "is_published", "-posted_at"], name="idx_job_feed"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["company", "status"], name="idx_job_company_status"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["needs_review", "-first_seen_at"], name="idx_job_review_queue"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["content_hash"], name="idx_job_content_hash"),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_deleted", False), models.Q(("source_job_id", ""), _negated=True)
                ),
                fields=("company", "source_job_id"),
                name="uniq_company_source_job_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("company", "title_normalized", "normalized_source_url"),
                name="uniq_company_title_sourceurl",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(("missing_count__lte", 3)), name="job_missing_count_max"
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "closed"), _negated=True),
                    ("closed_at__isnull", False),
                    _connector="OR",
                ),
                name="closed_job_requires_closed_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("salary_min__isnull", True),
                    ("salary_max__isnull", True),
                    ("salary_max__gte", models.F("salary_min")),
                    _connector="OR",
                ),
                name="job_salary_range_sane",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(("extraction_confidence__lte", 100)), name="job_confidence_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("job", "user"),
                name="uniq_open_report_per_user_job",
            ),
        ),
        migrations.AddIndex(
            model_name="jobstatusevent",
            index=models.Index(fields=["job", "-created_at"], name="idx_job_status_timeline"),
        ),
        migrations.AddConstraint(
            model_name="savedjob",
            constraint=models.UniqueConstraint(
                fields=("user", "job"), name="uniq_saved_job_per_user"
            ),
        ),
    ]
