# Generated by Django 5.2.17 on 2026-09-03 08:56

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_company_company_name_trgm"),
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobreport",
            old_name="comment",
            new_name="detail",
        ),
        migrations.RemoveField(
            model_name="savedjob",
            name="note",
        ),
        migrations.AddField(
            model_name="job",
            name="description_html_sanitized",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="savedjob",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="jobreport",
            name="reason",
            field=models.CharField(
                choices=[
                    ("expired", "Expired"),
                    ("broken_link", "Broken Link"),
                    ("wrong_details", "Wrong Details"),
                    ("duplicate", "Duplicate"),
                    ("spam", "Spam"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("reviewing", "Reviewing"),
                    ("resolved", "Resolved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="open",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass("title", name="gin_trgm_ops"),
                name="job_title_trgm",
            ),
        ),
        migrations.AddIndex(
            model_name="jobreport",
            index=models.Index(
                fields=["status", "-created_at"], name="idx_jobreport_status_created"
            ),
        ),
        migrations.AddIndex(
            model_name="savedjob",
            index=models.Index(fields=["user", "-created_at"], name="idx_savedjob_user_created"),
        ),
    ]
