# Generated by Django 5.2.17 on 2026-09-03 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_backfill_description_html_sanitized"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="job",
            name="idx_job_search_vector",
        ),
        migrations.RemoveField(
            model_name="job",
            name="search_vector",
        ),
    ]
