# Generated by Django 5.2.17 on 2026-09-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_backfill_job_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="parser_version",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
