# Generated by Django 5.2.17 on 2026-09-02 13:25

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0004_alter_company_detection_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapeRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[("schedule", "Schedule"), ("manual", "Manual")],
                        default="schedule",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("jobs_found", models.PositiveIntegerField(default=0)),
                ("jobs_added", models.PositiveIntegerField(default=0)),
                ("jobs_updated", models.PositiveIntegerField(default=0)),
                ("jobs_unchanged", models.PositiveIntegerField(default=0)),
                ("jobs_missing", models.PositiveIntegerField(default=0)),
                ("jobs_reopened", models.PositiveIntegerField(default=0)),
                ("error", models.JSONField(default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrape_runs",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScrapeError",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=1000)),
                ("error_type", models.CharField(max_length=80)),
                ("message", models.TextField()),
                ("traceback", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrape_errors",
                        to="companies.company",
                    ),
                ),
                (
                    "scrape_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="scraping.scraperun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
