# Generated by Django 5.2.17 on 2026-09-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scraperun",
            name="verdict",
            field=models.CharField(
                choices=[
                    ("TRUSTED", "Trusted"),
                    ("QUARANTINED", "Quarantined"),
                    ("UNTRUSTED", "Untrusted"),
                ],
                db_index=True,
                default="TRUSTED",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="scraperun",
            name="verdict_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
