# Generated by Django 5.2.17 on 2026-09-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0002_scraperun_verdict_scraperun_verdict_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scraperun",
            name="verdict",
            field=models.CharField(
                choices=[
                    ("trusted", "Trusted"),
                    ("quarantined", "Quarantined"),
                    ("untrusted", "Untrusted"),
                ],
                db_index=True,
                default="trusted",
                max_length=16,
            ),
        ),
    ]
