# Generated by Django 5.2.17 on 2026-09-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0003_alter_scraperun_verdict"),
    ]

    operations = [
        migrations.AddField(
            model_name="scraperun",
            name="parser_version",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
