# Generated by Django 5.2.17 on 2026-09-05 22:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_company_company_name_trgm"),
        ("scraping", "0004_scraperun_parser_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapeArtifact",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=1000)),
                ("content_gzip", models.BinaryField()),
                ("content_type", models.CharField(blank=True, max_length=100)),
                (
                    "byte_size",
                    models.PositiveIntegerField(help_text="Original uncompressed byte size"),
                ),
                ("truncated", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrape_artifacts",
                        to="companies.company",
                    ),
                ),
                (
                    "scrape_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="scraping.scraperun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["scrape_run", "-created_at"], name="scraping_sc_scrape__b6df9f_idx"
                    ),
                    models.Index(
                        fields=["company", "-created_at"], name="scraping_sc_company_d5a8ce_idx"
                    ),
                ],
            },
        ),
    ]
