# Generated by Django 5.2.17 on 2026-09-06 08:58

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0005_scrapeartifact"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceFetchState",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("url_hash", models.CharField(max_length=64, unique=True)),
                ("url", models.TextField()),
                ("etag", models.CharField(blank=True, max_length=256)),
                ("last_modified", models.CharField(blank=True, max_length=128)),
                ("body_hash", models.CharField(blank=True, max_length=64)),
                ("last_fetched_at", models.DateTimeField()),
                ("hit_count", models.PositiveIntegerField(default=0)),
                ("miss_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-last_fetched_at"],
                "indexes": [
                    models.Index(fields=["url_hash"], name="scraping_so_url_has_52a2cd_idx"),
                    models.Index(fields=["last_fetched_at"], name="scraping_so_last_fe_b2e995_idx"),
                ],
            },
        ),
    ]
