# Generated by Django 5.2.17 on 2026-09-03 21:59

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConductingBody",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(blank=True, max_length=50)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "body_type",
                    models.CharField(
                        choices=[
                            ("central", "Central"),
                            ("state", "State"),
                            ("banking", "Banking"),
                            ("railway", "Railway"),
                            ("defence", "Defence"),
                            ("testing_agency", "Testing Agency"),
                        ],
                        max_length=20,
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=100)),
                ("website", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "conducting bodies",
                "indexes": [
                    models.Index(fields=["slug"], name="exams_condu_slug_3beaf3_idx"),
                    models.Index(fields=["is_active"], name="exams_condu_is_acti_460cb1_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(blank=True, max_length=50)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("civil_services", "Civil Services"),
                            ("banking", "Banking"),
                            ("railway", "Railway"),
                            ("ssc", "SSC"),
                            ("teaching", "Teaching"),
                            ("defence", "Defence"),
                            ("engineering", "Engineering"),
                            ("medical", "Medical"),
                            ("law", "Law"),
                            ("state_psc", "State PSC"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("national", "National"), ("state", "State")], max_length=10
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("official_url", models.URLField(blank=True)),
                ("typical_month", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "conducting_body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exams",
                        to="exams.conductingbody",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamCycle",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("year", models.PositiveIntegerField()),
                ("cycle_label", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("announced", "Announced"),
                            ("notification_out", "Notification Out"),
                            ("applications_open", "Applications Open"),
                            ("applications_closed", "Applications Closed"),
                            ("admit_card_out", "Admit Card Out"),
                            ("exam_conducted", "Exam Conducted"),
                            ("result_out", "Result Out"),
                            ("cancelled", "Cancelled"),
                            ("postponed", "Postponed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notification_date", models.DateField(blank=True, null=True)),
                ("application_start", models.DateField(blank=True, null=True)),
                ("application_end", models.DateField(blank=True, null=True)),
                ("fee_last_date", models.DateField(blank=True, null=True)),
                ("correction_window_start", models.DateField(blank=True, null=True)),
                ("correction_window_end", models.DateField(blank=True, null=True)),
                ("result_date", models.DateField(blank=True, null=True)),
                ("vacancy_count", models.PositiveIntegerField(blank=True, null=True)),
                ("official_notification_url", models.URLField(blank=True)),
                ("notification_pdf_url", models.URLField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                ("extraction_confidence", models.PositiveSmallIntegerField(default=0)),
                ("verified_by_human", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycles",
                        to="exams.exam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamEligibility",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("min_age", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_age", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("age_as_on_date", models.DateField(blank=True, null=True)),
                ("age_relaxation", models.JSONField(default=dict)),
                ("attempts_general", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("attempts_obc", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("attempts_sc_st", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("attempts_pwbd", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("min_qualification", models.TextField(blank=True)),
                ("allow_final_year_appearing", models.BooleanField(default=False)),
                ("nationality_note", models.TextField(blank=True)),
                ("physical_standards", models.JSONField(blank=True, null=True)),
                ("verified_by_human", models.BooleanField(default=False)),
                ("source_url", models.URLField(blank=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility",
                        to="exams.examcycle",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "exam eligibility",
            },
        ),
        migrations.CreateModel(
            name="ExamStage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("stage_order", models.PositiveSmallIntegerField()),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("online_cbt", "Online CBT"),
                            ("offline_omr", "Offline OMR"),
                            ("descriptive", "Descriptive"),
                            ("interview", "Interview"),
                            ("physical", "Physical"),
                            ("document", "Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_start", models.DateField(blank=True, null=True)),
                ("date_end", models.DateField(blank=True, null=True)),
                ("is_date_tentative", models.BooleanField(default=True)),
                ("admit_card_date", models.DateField(blank=True, null=True)),
                ("city_intimation_date", models.DateField(blank=True, null=True)),
                ("result_date", models.DateField(blank=True, null=True)),
                ("duration_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("total_marks", models.PositiveIntegerField(blank=True, null=True)),
                ("negative_marking", models.TextField(blank=True)),
                ("is_qualifying_only", models.BooleanField(default=False)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="exams.examcycle",
                    ),
                ),
            ],
            options={
                "ordering": ["stage_order"],
            },
        ),
        migrations.CreateModel(
            name="ExamDateChange",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("field_name", models.CharField(max_length=50)),
                ("old_value", models.TextField()),
                ("new_value", models.TextField()),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("source_url", models.URLField(blank=True)),
                (
                    "detected_by",
                    models.CharField(
                        choices=[
                            ("scrape", "Scrape"),
                            ("human", "Human"),
                            ("corrigendum", "Corrigendum"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_changes",
                        to="exams.examcycle",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_changes",
                        to="exams.examstage",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedExam",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("notify", models.BooleanField(default=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="exams.exam",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_exams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["category", "level"], name="exams_exam_categor_be4247_idx"),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="exam_name_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="examcycle",
            index=models.Index(
                fields=["status", "-application_end"], name="exams_examc_status_538fd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examcycle",
            index=models.Index(
                fields=["is_published", "-notification_date"], name="exams_examc_is_publ_ef8adb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="examcycle",
            constraint=models.CheckConstraint(
                condition=models.Q(("extraction_confidence__range", (0, 100))),
                name="extraction_confidence_range",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examcycle",
            unique_together={("exam", "year", "cycle_label")},
        ),
        migrations.AlterUniqueTogether(
            name="examstage",
            unique_together={("cycle", "stage_order")},
        ),
        migrations.AlterUniqueTogether(
            name="savedexam",
            unique_together={("user", "exam")},
        ),
    ]
