# Generated by Django 5.2.17 on 2026-09-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="examcycle",
            name="extraction_confidence_range",
        ),
        migrations.AddConstraint(
            model_name="examcycle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("extraction_confidence__gte", 0), ("extraction_confidence__lte", 100)
                ),
                name="extraction_confidence_range",
            ),
        ),
    ]
