# Generated by Django 5.2.17 on 2026-09-04 10:32

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0002_remove_examcycle_extraction_confidence_range_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="conductingbody",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="conductingbody_name_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddConstraint(
            model_name="examcycle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_published", False), ("verified_by_human", True), _connector="OR"
                ),
                name="examcycle_published_requires_verification",
            ),
        ),
    ]
