# Generated by Django 5.2.17 on 2026-08-19 14:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "actor_label",
                    models.CharField(
                        blank=True,
                        help_text='Denormalized "email (role)" so history survives user deletion.',
                        max_length=160,
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=64)),
                ("app_label", models.CharField(blank=True, max_length=64)),
                ("model_name", models.CharField(blank=True, max_length=64)),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stringified PK (UUID-friendly).",
                        max_length=255,
                    ),
                ),
                ("object_repr", models.CharField(blank=True, max_length=240)),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("changed_fields", models.JSONField(default=list)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("API", "API"),
                            ("SYSTEM", "System"),
                            ("CELERY", "Celery"),
                            ("MANAGEMENT_COMMAND", "Management command"),
                        ],
                        default="SYSTEM",
                        max_length=24,
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("request_id", models.CharField(blank=True, max_length=64)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = system/Celery actor.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["app_label", "model_name", "object_id"],
                        name="audit_logs__app_lab_3f3f04_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"], name="audit_logs__action_70fdcf_idx"
                    ),
                ],
            },
        ),
    ]
